### ISSUE TITLE
Libmincrypt without node-gyp

### ISSUE THREAD

**Issue by cstyan** [appium/node-adb-client#4]
Node-gyp is being deprecated in favour of something(?) else, so we should compile the libmincrypt dependency to create JS bindings using whatever the new tools are.

**Comment by konobi** [comment]
I haven't heard of node-gyp being deprecated. The bindings could probably do with an update to use the npm package 'nan'. This should allow for multiple versions of node.

**Comment by konobi** [comment]
I also note that the documentation in the README says to use node-gyp directly after install. This isn't needed. The top gyp file should see the libmincrypt gyp file as a dependency and build it statically into the binding objectfile.

**Comment by cstyan** [comment]
I was told the way C bindings were written was changing in new versions of node, but that could be incorrect.  I wasn't able to find what the new way of writing C bindings was going to be, so I'll take a look at `nan`.  

I'm not sure what you mean but the nod needing to run node-gyp after npm install.

**Comment by konobi** [comment]
There is always a mismatch between different node versions as the node/v8 API/ABI change over time. However, this is where 'nan' comes in as it provides macros, etc. so that one version of the code will work across multiple node versions.

`npm install` will run node-gyp when needed, it's not a necessary step during install, only during development.

I also note that there's some missing licensing for some of the pre-existing code. mincrypt is directly from the android project.

**Comment by cstyan** [comment]
Okay, that's what I was missing.  `npm install` will build the bindings for libmincrypt, but I couldn't find a way to get gulp to build call the node-gyp build for me.

What licensing is missing? I've included the license from AOSP [here](https://github.com/appium/node-adb-client/blob/master/deps/libmincrypt/NOTICE).  Do I need a different license type when I'm using their library?
